//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockBoy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public decimal Article_id { get; set; }
        public string Open_tag { get; set; }
        public Nullable<System.DateTime> Article_Date { get; set; }
        public string Article_Title { get; set; }
        public string Article_Text { get; set; }
        public string Article_Img { get; set; }
        public Nullable<System.DateTime> add_date { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string edit_ip { get; set; }
    }
}
